### ISSUE TITLE
 TypeError: this.rotate is not a function. (In 'this.rotate(i,e)', 'this.rotate' is undefined)

### ISSUE THREAD

**Issue by akumatus** [wagerfield/parallax#173]
<img width="998" alt="2017-03-01 3 41 00" src="https://cloud.githubusercontent.com/assets/12724894/23450569/effd432e-fe96-11e6-8edb-e0335759fd7c.png">

This happens in iphone 6 & iphone 6 plus, making mobile browsers crash and ios system restart. But in iphone 5s or other android browsers,  parallax.js works fine with no error reports.

Is there any memory problems when number of layers getting huge? I suppose that I have more than 30 layers.

Appreciate for your reply.

**Comment by RRorg** [comment]
The whole browser crashes? That's not good.

I'll add a test case for this and check it out!

**Comment by akumatus** [comment]
It's very nice of you to answer my questions. Thanks a lot. 

This crash mainly happens in iphone 6 plus. Then I tried to annotate different part of my code to find out which part causes this problem. Here is my code:
```html
<ul id="scene">
        <li class="layer" data-depth="0.1">
            <div class="mountain-15"></div>
        </li>
        <li class="layer" data-depth="0.12">
            <div class="mountain-14"></div>
        </li>
        <li class="layer" data-depth="0.15">
            <div class="mountain-13"></div>
        </li>
        <li class="layer" data-depth="0.18">
            <div class="mountain-12"></div>
        </li>
        <li class="layer" data-depth="0.20">
            <div class="mountain-11"></div>
        </li>
        <li class="layer" data-depth="0.25">
            <div class="mountain-10"></div>
        </li>
        <li class="layer" data-depth="0.26">
            <div class="mountain-9"></div>
        </li>
        <li class="layer" data-depth="0.28">
            <div class="mountain-8"></div>
        </li>
        <li class="layer" data-depth="0.31">
            <div class="mountain-7"></div>
        </li>
        <li class="layer" data-depth="0.33">
            <div class="mountain-6"></div>
        </li>
        <li class="layer" data-depth="0.36">
            <div class="mountain-5"></div>
        </li>
        <li class="layer" data-depth="0.37">
            <div class="mountain-4"></div>
        </li>
        <li class="layer" data-depth="0.40">
            <div class="mountain-3"></div>
        </li>
        <li class="layer" data-depth="0.42">
            <div class="mountain-2"></div>
        </li>
        <li class="layer" data-depth="0.5">
            <div class="mountain-1"></div>
        </li>
<ul>
```

```less
  @ppr: 1080px/10/1rem;
  @widths: 671px, 755px,  1192px, 506px,  506px,  410px,  1379px, 259px,  794px,  460px,  1192px, 722px,  460px,  671px,  794px;
  @heights: 68px, 131px,  83px,   131px,  229px,  54px,   191px,  44px,   60px,   99px,   90px,   36px,   99px,   68px,   68px;
  @tops:  2145px, 2079px, 2109px, 1964px, 1880px, 1986px, 1861px, 1929px, 1915px, 1897px, 1819px, 1833px, 1741px, 1692px, 1672px;
  @lefts:   13px, 136px,  622px,  1763px, 426px,  594px,  932px,  1252px, 1007px, 13px,   -21px,  637px,  1405px, 784px,  1346px;
  .generate-mountains(@n, @i: 1) when (@i =< @n) {
    .mountain-@{i} {
      position: absolute;
      top: extract(@tops, @i)/@ppr;
      left: extract(@lefts, @i)/@ppr;
      width: extract(@widths, @i)/@ppr;
      height: extract(@heights, @i)/@ppr;
      background: url("../images/mountain-@{i}.png") no-repeat center;
      background-size: contain;
    }
    .generate-mountains(@n, (@i + 1));
  }

  .generate-mountains(15);
```
I guess those large numbers of mountain layers cause the crash, but still I cant't find out why. The safari just indicates that there is error in my page and trying to reload it.

**Comment by akumatus** [comment]
After merging different layers with analogical data-depth and changing my css layouts , the probability of crash has decreased incredibly. Advanced layouts looks like below:
After:
```less
  #scene {
    position: relative;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
  }
```

Before:
```less
  #scene {
    position: relative;
    width: 2310px/@ppr;
    height: 2480px/@ppr;
    top: -475px/@ppr;
    left: -615px/@ppr;
  }
```
In a word, I suppose it is not parallax itself causes the crash. The layouts should takes the primary responsibility.
